# FROM ... choose your base image

# WORKDIR ... set the working directory

# COPY ... your server files into the container

# RUN ... perform other actions to ready your server (i.e. installations)

# EXPOSE ... the port your server listens on

# ENV ... set environment variables if necessary

# CMD ... run your server
