# Use AlmaLinux as the base image
FROM almalinux:9

# Set the working directory
WORKDIR /app

# Install Python 3, and build dependencies
# RUN dnf install ...

# Install Flask
# RUN pip ...

# Copy the project files into the container
COPY ./??? /app

# Expose port to allow access to the Flask service
# EXPOSE ????

# How do we run the Flask app?
CMD [ "???", "app.py"]
